version: '3.8'

services:
  server:
    container_name: server
    build: .
    ports:
      - "9990:9990"
    command: python main.py
    volumes:
      - .:/server
      - /tmp/app/mysqld:/run/mysqld
    depends_on:
      - mysql
    networks:
      - server-mysql
    restart: always


  mysql:
    image: mysql:8.0
    container_name: dev_mysql
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOTPASSWORD}
    networks:
      - awesome_network
      - server-mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_phpmyadmin
    ports:
      - '9090:80'
    environment:
      PMA_HOST: mysql
      PMA_PORT: ${MYSQL_PORT}
    networks:
      - awesome_network
  
networks:
  awesome_network:
    name: awesome_network
    driver: bridge
  server-mysql:
    name: server-mysql
    driver: bridge